services:
  app:
    image: avalonia_tutorial
    container_name: getstartedapp_dev2
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "dotnet restore && dotnet build --configuration Development && dotnet run"
    ports:
      - "8080:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development