FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . ./

RUN curl -fsSL https://code-server.dev/install.sh | sh

# Install the Avalonia VS Code extension
RUN code-server --install-extension AvaloniaTeam.vscode-avalonia

# Restore and build the project for development
RUN dotnet restore
RUN dotnet build --configuration Development

# Expose port for Avalonia UI preview 
EXPOSE 8080

